[package]
name = "cargo-errorbook"
version = "0.0.1"
authors = ["Giles Cope <gilescope@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = "*"
cargo_metadata = "*"
